# Generated by Django 5.1.2 on 2024-10-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0001_initial'),
        ('places', '0002_alter_comment_options_remove_place_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterField(
            model_name='placecollection',
            name='places',
            field=models.ManyToManyField(related_name='collections', to='places.place'),
        ),
    ]
