# Generated by Django 5.1.2 on 2024-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0002_collection_remove_placecollection_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='place_images/')),
                ('rating_avg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(related_name='collections', to='placeCollection.place'),
        ),
    ]
