# Generated by Django 5.1.2 on 2024-10-27 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0002_delete_place_alter_placecollection_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='placeCollection.collection')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='placeCollection.place')),
            ],
            options={
                'unique_together': {('collection', 'place')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(related_name='collections', through='placeCollection.CollectionItem', to='placeCollection.place'),
        ),
        migrations.DeleteModel(
            name='PlaceCollection',
        ),
    ]
