# Generated by Django 5.1.2 on 2024-10-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0003_place_collection_collectionitem_collection_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
