# Generated by Django 5.1.2 on 2024-10-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0003_place_collection_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='places',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
