# Generated by Django 5.1.2 on 2024-10-26 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0004_remove_collection_places_delete_place'),
        ('places', '0002_alter_comment_options_remove_place_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='placeCollection.collection')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='places.place')),
            ],
            options={
                'unique_together': {('collection', 'place')},
            },
        ),
    ]
