# Generated by Django 5.1.2 on 2024-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeCollection', '0006_alter_collection_user'),
        ('places', '0002_alter_comment_options_remove_place_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='places',
            field=models.ManyToManyField(related_name='collections', through='placeCollection.CollectionItem', to='places.place'),
        ),
    ]
