# Generated by Django 5.1.2 on 2024-10-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecollections', '0002_place_placecollection_delete_placecollections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placecollection',
            name='user',
        ),
    ]
