# Generated by Django 5.1.1 on 2024-10-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlakumlakuuser',
            name='profile_picture',
            field=models.ImageField(default='static/img/noneicon.png', upload_to=''),
        ),
    ]
