# Generated by Django 5.1 on 2024-10-25 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_created_at_journal_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjournal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedjournal',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='savedjournal',
            name='user',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='SavedJournal',
        ),
    ]
