# Generated by Django 5.1.1 on 2024-10-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mlakumlakuuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlakumlakuuser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mlakumlakuuser',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
