# Generated by Django 5.1 on 2024-10-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_savedjournal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='journal',
            name='souvenir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.souvenir'),
        ),
    ]
