# Generated by Django 5.1 on 2024-10-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_souvenir_alter_journal_title_journal_souvenir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souvenir',
            name='rating',
        ),
        migrations.AddField(
            model_name='souvenir',
            name='place_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
