# Generated by Django 5.1.1 on 2024-10-27 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mlakumlakuuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlakumlakuuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
